name: Download Logos

on:
  schedule:
    - cron: '0 2 * * 0' # Runs every Sunday at 2 AM UTC
  workflow_dispatch: # Allows manual triggering from Actions tab

permissions:
  contents: write # Needed to commit changes

jobs:
  download-logos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for proper commits

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Create scripts directory if it doesn't exist
        run: mkdir -p scripts

      - name: Make download script executable
        run: chmod +x download-logos.js

      - name: Download logos from URLs
        run: node download-logos.js

      - name: Check for changes
        id: git-check
        run: |
          git diff --exit-code data/startups.json assets/logos/ || echo "changed=true" >> $GITHUB_OUTPUT

      - name: Commit and push changes
        if: steps.git-check.outputs.changed == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add data/startups.json assets/logos/
          git commit -m "chore: download startup logos from URLs

          - Downloaded logos from logoUrl fields
          - Updated startups.json with local paths
          - Automated by GitHub Actions"
          git push

      - name: No changes detected
        if: steps.git-check.outputs.changed != 'true'
        run: echo "✅ No new logos to download"
